name: record
description: record package modified by the Fajurion team.
version: 4.4.5
homepage: https://github.com/llfbandit/record/tree/master/record
publish_to: 'none' # I haven't read about this yet, but in case the owner of record sees this, just use your own files.

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter

  record_platform_interface: ^0.5.0
  record_web:
    path: ../record_web
  record_windows:
    path: ../record_windows
  record_macos:
    path: ../record_macos
  record_linux:
    path: ../record_linux

dev_dependencies:
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^2.0.0

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.llfbandit.record
        pluginClass: RecordPlugin
      ios:
        pluginClass: RecordPlugin
      web:
        default_package: record_web
      windows:
        default_package: record_windows
      macos:
        default_package: record_macos
      linux:
        default_package: record_linux
